print('ola mundo')
print('Python 2 numeros')
print()
print("unindo textos com + print('5'+'7')")
print('5'+'7')
print("unindo textos com + print('5+7')")
print('5+7')

print("unindo textos com , print('5','7'),a virgula põe um espaço entre os numeros")
print('5','7')
print()
print('unindo textos com + print("5"+"7")')
print('5'+'7')
print('unindo textos com , print("5","7"),a virgula põe um espaço entre os numeros')
print("5","7")
print()
print('somando os numeros com print(5+7)')
print(5+7)
