print ('********************* DESAFIO 01 *********************')
print()
nome= input ('Qual seu nome?')
print('Ola',nome,'seja bem vindo a programação Python')
print()
print ('********************* DESAFIO 02 *********************')
print()
dia = input('Que dia voce nasceu? ')
mes = input('Que mes voce nasceu? ')
ano = input('Que ano voce nasceu? ')
print('Voce nasceu em ',dia,'de',mes,'de',ano,'correto?')
print()
print ('********************* DESAFIO 03 *********************')
print()
numero1 = int(input('Qual o primeiro numero ? '))
numero2 = int(input('Qual o segundo numero ? '))
soma = numero1+numero2
print ('a soma do primeiro numero + o segundo numero é',soma)
print ('a soma do primeiro numero + o segundo numero é',numero1+numero2)
print ('a soma + a soma é',soma+soma)
print ('a soma + primeiro numero é',soma+numero1)
print ('a soma + segundo numero é',soma+numero2)


