print ('====== DESAFIO 03 ======')
print('para input e função com numeros voce precisa definir o tipo de variavel, "objeto"')
print()
numero1=input ('Digite um número ')
numero2=input ('Digite outro número ')
print ('A soma é', numero1+numero2)
print('Aqui voce define o tipo de objeto como inteiro')
numero1=int(input('Digite um número '))
numero2=int(input('Digite outro número '))
print ('A soma é', numero1+numero2)
