n = input('Digite algo, espaço ou press enter: ')
print('O que voce digitou é maiúscula? ', n.isupper())
print('O que digitou é minúscula? ', n.islower())
print('O que digitou é numérico? ', n.isnumeric())
print('O que digitou é alfanumérico? ', n.isalnum())
print('O que voce digitou é ascii? ', n.isascii())
print('O que digitou é decimal? ', n.isdecimal())
print('O que digitou é alfabetico? ', n.isalpha())
print('O que digitou é imprimivél? ', n.isprintable())
print('O que digitou é um digito? ', n.isdigit())
print('O que digitou é um identificador? ', n.isidentifier())
print('O que voce digitou é um espaço? ', n.isspace())
print('O que voce digitou é um título?', n.istitle())
